title: Certificacion Java 8
description: Camino a la certificación Java SE 8 Programmer I
baseurl:
url: http://windoctor.github.io/certificacion-java-8/
avatar: /assets/img/java-icon.png
favicon: # path/to/favicon for site. e.g. /assets/img/favicon.ico
google_analytics: # google analytics id
disqus_shortname: ascariromo


    
